[server]
headless = true
address = "0.0.0.0"
port = 8501
maxUploadSize = 102400

[theme]
base = "dark"
primaryColor = "#FF6B6B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
